ALL_DATA_FILE_PATH = 'data/mu/all.dta'
ALL_INDEX_FILE_PATH = 'data/mu/all.idx'
BASE_DATA_FILE_PATH = 'data/mu/base.dta'
HIDDEN_DATA_FILE_PATH = 'data/mu/hidden.dta'
PROBE_DATA_FILE_PATH = 'data/mu/probe.dta'
